spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useSSL=false
    username: root
    password: Amysm9022@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    auditing:
      enabled: true

  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    org.hibernate.SQL: debug
    org:
      springframework:
        data:
          jpa:
            domain:
              support:
                AuditingHandler: DEBUG
